server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    punlish-confirms: true

